// framework-sdks/nextjs-package/components/toolbar.tsx
import Script from 'next/script';
import React from 'react';

export interface ToolbarProps {
	projectId: string;
	branch?: string;
}

export function TunnelToolbar({
	projectId,
	branch,
	...additionalProps
}: ToolbarProps) {
	const src = 'release' in additionalProps && additionalProps.release === null ?
		'https://tunnel.test/__tunnel/script.js' :
		'release' in additionalProps && additionalProps.release === 'staging' ?
		'https://staging.tunnel.dev/__tunnel/script.js' :
		'https://tunnel.dev/__tunnel/script.js';

	const scriptProps = {
		src,
		'data-project-id': projectId,
		'data-branch': branch,
		...('release' in additionalProps ?
			{ 'data-release': additionalProps.release ?? 'development' } :
			{}),
	};

	return <Script strategy="afterInteractive" {...scriptProps} />;
}

// framework-sdks/svelte-package/components/toolbar.svelte
<script lang='ts'>
import { onMount, onDestroy } from 'svelte';
import { RELEASE } from '@-/env/app'

let script: HTMLScriptElement | undefined;

export let projectId: string;
export let branch: string | undefined;

onMount(() => {
	const script = document.createElement('script');

	const src =
		RELEASE === null ?
			'https://tunnelapp.test/__tunnel/script.js' :
			RELEASE === 'staging' ?
			'https://staging.tunnel.dev/__tunnel/script.js' :
			'https://tunnel.dev/__tunnel/script.js';

	script.src = src;
	script.dataset.projectId = projectId;
	if (branch !== undefined) {
		script.dataset.branch = branch;
	}

	script.async = true;

	document.body.append(script);
})

onDestroy(() => {
	script?.remove();
})
</script>
