// framework-sdks/react-package/components/toolbar.tsx
import { useEffect } from 'react';

export interface ToolbarProps {
	projectId: string;
	branch?: string;
}

export function TunnelToolbar({
	projectId,
	branch,
	...additionalProps
}: ToolbarProps) {
	useEffect(() => {
		const script = document.createElement('script');

		const src =
			'release' in additionalProps && additionalProps.release === null ?
				'https://tunnel.test/__tunnel/script.js' :
				'release' in additionalProps && additionalProps.release === 'staging' ?
				'https://staging.tunnel.dev/__tunnel/script.js' :
				'https://tunnel.dev/__tunnel/script.js';

		script.src = src;
		script.dataset.projectId = projectId;
		if (branch !== undefined) {
			script.dataset.branch = branch;
		}

		if ('release' in additionalProps && additionalProps.release !== null) {
			script.dataset.release = String(additionalProps.release);
		}

		script.async = true;

		document.body.append(script);

		return () => {
			script.remove();
		};
	}, []);

	return null;
}

// framework-sdks/svelte-package/components/toolbar.svelte
<script lang='ts'>
import { onMount, onDestroy } from 'svelte';
import { RELEASE } from '@-/env/app'

let script: HTMLScriptElement | undefined;

export let projectId: string;
export let branch: string | undefined;

onMount(() => {
	const script = document.createElement('script');

	const src =
		RELEASE === null ?
			'https://tunnelapp.test/__tunnel/script.js' :
			RELEASE === 'staging' ?
			'https://staging.tunnel.dev/__tunnel/script.js' :
			'https://tunnel.dev/__tunnel/script.js';

	script.src = src;
	script.dataset.projectId = projectId;
	if (branch !== undefined) {
		script.dataset.branch = branch;
	}

	script.async = true;

	document.body.append(script);
})

onDestroy(() => {
	script?.remove();
})
</script>
